// Code generated by protoc-gen-go. DO NOT EDIT.
// source: robot.proto

/*
Package robot is a generated protocol buffer package.

It is generated from these files:
	robot.proto

It has these top-level messages:
	Message
	SecretPart
*/
package robot

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	From        int64         `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	SecretParts []*SecretPart `protobuf:"bytes,2,rep,name=secret_parts,json=secretParts" json:"secret_parts,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Message) GetSecretParts() []*SecretPart {
	if m != nil {
		return m.SecretParts
	}
	return nil
}

type SecretPart struct {
	Index int64  `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Word  string `protobuf:"bytes,2,opt,name=word" json:"word,omitempty"`
}

func (m *SecretPart) Reset()                    { *m = SecretPart{} }
func (m *SecretPart) String() string            { return proto.CompactTextString(m) }
func (*SecretPart) ProtoMessage()               {}
func (*SecretPart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SecretPart) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SecretPart) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*SecretPart)(nil), "SecretPart")
}

func init() { proto.RegisterFile("robot.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xca, 0x4f, 0xca,
	0x2f, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xf2, 0xe5, 0x62, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e,
	0x4c, 0x4f, 0x15, 0x12, 0xe2, 0x62, 0x49, 0x2b, 0xca, 0xcf, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60,
	0x0e, 0x02, 0xb3, 0x85, 0xf4, 0xb8, 0x78, 0x8a, 0x53, 0x93, 0x8b, 0x52, 0x4b, 0xe2, 0x0b, 0x12,
	0x8b, 0x4a, 0x8a, 0x25, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0xb8, 0xf5, 0x82, 0xc1, 0x82, 0x01,
	0x40, 0xb1, 0x20, 0xee, 0x62, 0x38, 0xbb, 0x58, 0xc9, 0x8c, 0x8b, 0x0b, 0x21, 0x25, 0x24, 0xc2,
	0xc5, 0x9a, 0x99, 0x97, 0x92, 0x5a, 0x01, 0x35, 0x12, 0xc2, 0x01, 0xd9, 0x53, 0x9e, 0x5f, 0x94,
	0x02, 0x34, 0x8b, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x4e, 0x62, 0x03, 0xbb, 0xc6, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x03, 0x55, 0xad, 0xbd, 0x9c, 0x00, 0x00, 0x00,
}
