// Code generated by protoc-gen-go. DO NOT EDIT.
// source: robot.proto

/*
Package robot is a generated protocol buffer package.

It is generated from these files:
	robot.proto

It has these top-level messages:
	SecretPart
	GossipSummary
	GossipUpdate
*/
package robot

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SecretPart struct {
	Index int64  `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Word  string `protobuf:"bytes,2,opt,name=word" json:"word,omitempty"`
}

func (m *SecretPart) Reset()                    { *m = SecretPart{} }
func (m *SecretPart) String() string            { return proto.CompactTextString(m) }
func (*SecretPart) ProtoMessage()               {}
func (*SecretPart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SecretPart) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SecretPart) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

// A robot send his own indexes
type GossipSummary struct {
	Indexes []int64 `protobuf:"varint,1,rep,packed,name=indexes" json:"indexes,omitempty"`
}

func (m *GossipSummary) Reset()                    { *m = GossipSummary{} }
func (m *GossipSummary) String() string            { return proto.CompactTextString(m) }
func (*GossipSummary) ProtoMessage()               {}
func (*GossipSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GossipSummary) GetIndexes() []int64 {
	if m != nil {
		return m.Indexes
	}
	return nil
}

// A robot responds his own secretParts (index, word)
type GossipUpdate struct {
	SecretParts []*SecretPart `protobuf:"bytes,1,rep,name=secret_parts,json=secretParts" json:"secret_parts,omitempty"`
}

func (m *GossipUpdate) Reset()                    { *m = GossipUpdate{} }
func (m *GossipUpdate) String() string            { return proto.CompactTextString(m) }
func (*GossipUpdate) ProtoMessage()               {}
func (*GossipUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GossipUpdate) GetSecretParts() []*SecretPart {
	if m != nil {
		return m.SecretParts
	}
	return nil
}

func init() {
	proto.RegisterType((*SecretPart)(nil), "SecretPart")
	proto.RegisterType((*GossipSummary)(nil), "GossipSummary")
	proto.RegisterType((*GossipUpdate)(nil), "GossipUpdate")
}

func init() { proto.RegisterFile("robot.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xca, 0x4f, 0xca,
	0x2f, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe3, 0xe2, 0x0a, 0x4e, 0x4d, 0x2e, 0x4a,
	0x2d, 0x09, 0x48, 0x2c, 0x2a, 0x11, 0x12, 0xe1, 0x62, 0xcd, 0xcc, 0x4b, 0x49, 0xad, 0x90, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0x70, 0x84, 0x84, 0xb8, 0x58, 0xca, 0xf3, 0x8b, 0x52, 0x24,
	0x98, 0x80, 0x82, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x26, 0x17, 0xaf, 0x7b, 0x7e, 0x71, 0x71, 0x66,
	0x41, 0x70, 0x69, 0x6e, 0x6e, 0x62, 0x51, 0xa5, 0x90, 0x04, 0x17, 0x3b, 0x58, 0x75, 0x6a, 0x31,
	0x50, 0x33, 0x33, 0x50, 0x33, 0x8c, 0xab, 0x64, 0xc7, 0xc5, 0x03, 0x51, 0x1a, 0x5a, 0x90, 0x92,
	0x58, 0x92, 0x2a, 0xa4, 0xc7, 0xc5, 0x53, 0x0c, 0xb6, 0x32, 0xbe, 0x00, 0x68, 0x27, 0x44, 0x39,
	0xb7, 0x11, 0xb7, 0x1e, 0xc2, 0x1d, 0x41, 0xdc, 0xc5, 0x70, 0x76, 0x71, 0x12, 0x1b, 0xd8, 0xa5,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x7a, 0x83, 0x4c, 0xb8, 0x00, 0x00, 0x00,
}
