// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v4.25.3
// source: proto/robot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Word          string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretPart) Reset() {
	*x = SecretPart{}
	mi := &file_proto_robot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretPart) ProtoMessage() {}

func (x *SecretPart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretPart.ProtoReflect.Descriptor instead.
func (*SecretPart) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{0}
}

func (x *SecretPart) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SecretPart) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

// A robot send his own indexes
type GossipSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indexes       []int64                `protobuf:"varint,1,rep,packed,name=indexes,proto3" json:"indexes,omitempty"`
	SenderId      int32                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipSummary) Reset() {
	*x = GossipSummary{}
	mi := &file_proto_robot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipSummary) ProtoMessage() {}

func (x *GossipSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipSummary.ProtoReflect.Descriptor instead.
func (*GossipSummary) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{1}
}

func (x *GossipSummary) GetIndexes() []int64 {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *GossipSummary) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

// A robot responds his own secretParts (index, word)
type GossipUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretParts   []*SecretPart          `protobuf:"bytes,1,rep,name=secret_parts,json=secretParts,proto3" json:"secret_parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipUpdate) Reset() {
	*x = GossipUpdate{}
	mi := &file_proto_robot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipUpdate) ProtoMessage() {}

func (x *GossipUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipUpdate.ProtoReflect.Descriptor instead.
func (*GossipUpdate) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{2}
}

func (x *GossipUpdate) GetSecretParts() []*SecretPart {
	if x != nil {
		return x.SecretParts
	}
	return nil
}

var File_proto_robot_proto protoreflect.FileDescriptor

var file_proto_robot_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x36, 0x0a, 0x0a, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x46, 0x0a, 0x0d, 0x47, 0x6f, 0x73,
	0x73, 0x69, 0x70, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x4b, 0x0a, 0x0c, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x61, 0x72,
	0x74, 0x52, 0x0b, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x73, 0x42, 0x17,
	0x5a, 0x15, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x62, 0x2d, 0x67, 0x6f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_robot_proto_rawDescOnce sync.Once
	file_proto_robot_proto_rawDescData = file_proto_robot_proto_rawDesc
)

func file_proto_robot_proto_rawDescGZIP() []byte {
	file_proto_robot_proto_rawDescOnce.Do(func() {
		file_proto_robot_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_robot_proto_rawDescData)
	})
	return file_proto_robot_proto_rawDescData
}

var file_proto_robot_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_robot_proto_goTypes = []any{
	(*SecretPart)(nil),    // 0: robots.proto.SecretPart
	(*GossipSummary)(nil), // 1: robots.proto.GossipSummary
	(*GossipUpdate)(nil),  // 2: robots.proto.GossipUpdate
}
var file_proto_robot_proto_depIdxs = []int32{
	0, // 0: robots.proto.GossipUpdate.secret_parts:type_name -> robots.proto.SecretPart
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_robot_proto_init() }
func file_proto_robot_proto_init() {
	if File_proto_robot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_robot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_robot_proto_goTypes,
		DependencyIndexes: file_proto_robot_proto_depIdxs,
		MessageInfos:      file_proto_robot_proto_msgTypes,
	}.Build()
	File_proto_robot_proto = out.File
	file_proto_robot_proto_rawDesc = nil
	file_proto_robot_proto_goTypes = nil
	file_proto_robot_proto_depIdxs = nil
}
